apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frontend-prometheus-scaler
  namespace: astronomy
spec:
  scaleTargetRef:
    name: frontend
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.astronomy.svc.cluster.local:9090
      # UPDATED QUERY: Using 'job' instead of 'service_name'
      query: sum(rate(http_server_request_duration_seconds_count{job="frontend"}[1m]))
      threshold: "10"
